.travis.yml
Dockerfile
mender-deb-package

Ported the toolchain change from mender-convert to the deb package, so
that we are consistent in the ARM support accross the mender offering.
Along the way:
* Build liblzma from source instead of using the Debian upstream pkg
* Hardcode deb package dependencies instead of using Debian helper
* Compile go code for ARM6 (to be consistent across mender products)
* Clean debug prints

Prepare deb package for ARMv6 devices (Raspberry Pi Zero W)

---

Dockerfile
mender-deb-package

Changelog: Move from locally compiled lzma library, to relying on the
Debian package.

MEN: 2728: ARM cross compile: align dependencies across components

---

debian/mender-client.dirs
debian/postinst
debian/postrm
debian/rules
tests/test_package_client.py

```
commit 2244db2b5e68476cd31be622b7a9ae8f11e56788
Author: Lluis Campos <lluis.campos@northern.tech>
Date:   Mon Oct 28 15:35:27 2019 +0100
Clean-up device_type file on purge in postrm step.
This file is created by mender setup in postinst step, so it should be
cleaned up accordignly on purge in postrm step.
commit e531df5f7e9e7b1785cf3ffd9033f5272171e260
Author: Lluis Campos <lluis.campos@northern.tech>
Date:   Mon Oct 28 15:40:32 2019 +0100
Rework current tests to use the new package in non-intreactive mode
This commit removes the extra configuration steps and the enable/start
of systemd service, as these are now handled on the deb pacakge install
and remove logic.
The installation of the pacakge is done in …
```

MEN-2419: Integration test for interactive install

---

mender-deb-package

Fix tag detection regex to accept build tags, tags can either be like 1.2.3 or 1.2.3-build4.

Fix tag detection regex to accept build tags

---

.gitlab-ci.yml

Allow integration tests failures on Pipeline
This is the only way (at the moment) to publish the deb packages for old
Mender client (i.e. 2.1.x).
A proper fix will be discussed and put in place with QA-123.

Allow integration tests failures on Pipeline

---

debian-master/postinst

Made device type default to hostname in postinstall script.
changelog: none
Signed-off-by: Alf-Rune Siqveland <alf.rune@northern.tech>

Rename Hosted Mender setup flag and set default device type

---

.gitlab-ci.yml
tests/test_package_client.py

The tests have been broken for a while, but because we were accepting failures in the Pipeline job it went unnoticed. This PR fixes the specific issues and disallow the job to fail from now on (there is a alternative method to skip tests if required).
See individual commits.

Fix acceptance tests

---

Dockerfile

Modify the code to better express the logic: the service file is
required for all debian-* directories except for 2.1.x, and on top of
that can be called mender-client.service or mender.service.

Fix systemd service missing issue for 2.3.x/2.2.x recipes

---

debian-master/control
debian-master/copyright
tests/test_package_client.py

* Update Copyright to 2020 and maintainer e-mail.
* Elevate to sudo the calls to cat mender.conf now that the file is protected.

License update + acceptance tests fix

---

Dockerfile
docker-mender-dist-packages

* Add --no-cache to the Docker build command
The image shall fetch Mender upstream on each build, so add an explicit
flag to disable cache. Mainly to help local builds, does not affect CI.
* Parametrize Docker base image
So that eventually we can reuse the same Dockerfile to build packages
for different Debian versions.

Minor improvements around Docker image build

---

.gitlab-ci.yml
mender-deb-package

The two first commits are just refactoring.
The last one is more of a question:
* Should this be published separately, as an option (Like I have done here)?
* Or should it be published alongside every build the script does?
I'm not really sure what is the preferred option here.

QA-214: Publish a 'latest' Mender deb package

---

.gitlab-ci.yml

Check build variables to be more strict on the publish policy: only
attempt including packages in stable which come from final tags.
Similarly, relax criteria in experimental so that it can fail when
master packages get rebuilt (which will happen very often).

[pipeline] Improve publish:s3:apt-repo script

---

.gitlab-ci.yml

So that we can download user specified versions from mender-convert or
possibly other scripts.

APT repository: keep unreferenced files

---

Dockerfile
mender-deb-package
recipes/mender-shell/debian-master/control

* [Dockerfile] Remove echo of private key
Probably a leftover from development debug.
* Bump bugfix version for master/experimental builds
So that 2.4.2~giti[...] evaluates as newer than 2.4.1 but still lower
than 2.4.2 (or 2.5.0).
* mender-shell: Set mender-client dependency to 2.4.2-git version
So that it can be installed in experimental distribution.
The specific version has been selected as what is mender master today,
so that it includes the recently merged DBus feature and the new
versioning scheme from mender-dist-packages (see 868b6b1).

mender-shell: Set mender-client dependency to 2.4.2-git version

---

Dockerfile

Switch to compressed download.
It seems like the download is timing out in CI, maybe because the
upstream server is having performance issues.

[Dockerfile] Download and extract Packages.gz

---

recipes/mender-client/debian-master/rules

In a way that the recipe becomes future ready for more install-* kind of
targets.

[mender-client rules] Add install-dbus target

---

.gitlab-ci.yml

When two pipelines run in parallel (which happens on releases) there is
a high change of corrupting the repository.
Prevent it by locking the S3 bucket that we are about to update.
Note that this is not atomic and there is a chance of forever block one
of the pipelines, in which case it will be killed by GitLab timeout. Not
a very high risk.

[pipeline] Add lock around APT repository update

---

tests/test_install_mender_sh.py

* [test_install_mender_sh.py] Enable all tests
Now that mender-connect 1.0.0 has been released.
* [test_install_mender_sh.py] De-scope some test cases
Remove the channel parametrization for test_client and test_connect,
reducing the overall test cases for this file from 9 to 5.
The channel switch is already tested in the main test case, and it is
very low risk to remove it from the others.
Currently the full test suite takes more than 1 hour, exceeding the
timeout in CI.

[test_install_mender_sh.py] Enable all tests

---

mender-deb-package
tests/test_package_addons.py

If we have requested to build master in the build parameters, we want
a SHA-based package version, even if it matches the tag exactly. This
is also expected by our tests, which fail without this fix.
However, the reported version by the tool should be the tag name, if
it's possible. So testing for this when building master is wrong,
because it can be both a tag name and a SHA, depending on what is
built.

Work around when master is exactly on a tag name.

---

Dockerfile
tests/test_package_client.py

The older client branch has no go module support, and hence the build fails.
Simply use the GO111MODULE=auto option, to handle both setups seamlessly.

Support building mender-client 2.3.x

---

mender-deb-package

This removes the https:// prefix from the repository name when cloning the repository

Remove the https:// prefix from the GOPATH

---

.gitlab-ci.yml
docker-mender-dist-packages
mender-deb-package
tests/test_dist_packages_versions.py
tests/test_package_client.py

Main commit is:
```
Append build revision to package versions
So that the same source (same git commit) can be rebuild and
re-published on experimental on changes from mender-dist-packages
repository.
```
And somewhat related:
```
[test] Create explicit test for package versions
After 83c1685, we are not really verifying the output of mender -version
on the target for master builds; so move out this part into a separate
explicit test and (once on it) verify all packages.
```

Append build revision to package versions

---

recipes/mender-connect/debian-master/control

This reverts commit 53d7891b84234ac10d1e8e071644a489d8dc3266.
Not necessary anymore after the official 2.5.0 release.

Revert "mender-shell: Set mender-client dependency to 2.4.2-git version"

---

.gitlab-ci.yml
docker-mender-dist-packages
mender-deb-package

* [pipeline] Do not accept failures on publish experimental packages
All packages are unique since fix in f742f1c, so this workaround is not
needed anymore.
Unfortunately, it has actually been hiding another issue.
* dpkg-buildpackage: Stop using --build=binary and let the caller specify
According to its man page, --build=binary is alias for --build=any,all
which resulted in the three `mender-client_..._<arch>.changes` files
containing the checksum for mender-client-dev and eventually making
reprepro fail when trying to upload the same package (-dev) twice!
Use instead "any" on the for loop for the architectures, and explicitly
pass "all" for the platform independent packages. This creates a
dedicated change files (`..._all.changes`) for the mender-client with only
the mender-client-dev …

Fix APT repo update for mender-client-dev package

---

Dockerfile

We require libssl1.1 >= 1.1.1 to enable ECC keys in the Mender Client.
This version of openssl is not available in stretch, thus we upgrade to
buster.
Requires: https://github.com/mendersoftware/mender-test-containers/pull/72

Upgrade the Dockerfile to Debian buster

---

.gitlab-ci.yml
scripts/install-mender.sh

MEN-4759: install-mender.sh: Support installing commercial packages
New flag --commercial to toggle the closed deb packages. It is meant to
be used only from Hosted Mender and requires --jwt-token argument.
The commercial deb packages are downloaded directly using curl and
installed using dpkg. Reworked a bit the existing lists of packages in
the script to have more meaningful purposes.
Other related changes:
* install-mender.sh: Require bash, which is already required by Mender
GUI during onboarding.
* pipeline: Make master/stable copies of packages. This is a short term
solution but required for the script to have well known URL paths

MEN-4759: install-mender.sh: Support installing commercial packages

---

scripts/install-mender.sh
tests/test_install_mender_sh.py

This gives the opportunity to the Mender GUI to offload the setup
details to the install script.
Two main changes:
* Run mender setup with args passed after `--` marker.
* Configure mender-connect for RPi on demo mode.

MEN-4452: Support running mender setup with user specified args

---

.gitlab-ci.yml

The idea is two have two sets of publish jobs: one manual and one
automatic controlled via env variable.
The old SKIP_TESTS variable is superseded by the new one, just with
inverse logic.
Additionally:
* pipeline: publish: Remove legacy "latest" copy and rename docs publish
Job publish:s3:legacy:mender-client:latest would make a copy for old
versions of mender-convert to install the client. Last version to use
this method was mender-convert 2.2.x, now EOL
On the other hand, the job lish:s3:legacy:mender-client had a misleading
name, as the published package is still in use for direct download from
the Mender Docs site, so rename it to be explicit.

QA-322: Align pipeline with Mender release process

---

scripts/install-mender.sh

If DEMO is not defined, the script would fail with:
`line 298: [: : integer expression expected`

MEN-5075: install-mender.sh: Fix script when not using --demo

---

.gitlab-ci.yml

Which was preventing build tags to override the "master" mender-monitor
package.

pipeline: fix typo in is_build_tag function

---

.gitlab-ci.yml

Using workaround #1 from https://gitlab.com/gitlab-com/gl-infra/production/-/issues/5590

GitLab intermittent networking fix: FF_NETWORK_PER_BUILD env var

---

.gitlab-ci.yml

The responsibility of the CI, from now on, is to copy the
to-be-published files into /incoming directory in the S3 bucket. The VM
takes it from there.

MC-5731: pipeline: Move APT repo management to dedicated VM

---

.gitlab-ci.yml

A clean-up from #133 (and #140).

pipeline: publish:s3:apt-repo: Clean-up unused GPG keys requirement

---

mender-deb-package

After the rework from 3eea53c, MENDER_PRIVATE_REPO_ACCESS_USER is
defined for all calls to mender-deb-package, so this if block needs to
be a bit smarter to only activate when it is actually in use (iow when
the user string is in the repository URL).

mender-deb-package: Modify logic to detect private repo URL

---

.gitlab-ci.yml
docker-build-package
tests/helpers.py

So that we clearly distinguish in CI the packages to be handled by the
APT repository processing script and not publish a commercial package by
mistake.

QA-351: Separate OS from commercial packages in output

---

mender-deb-package

With only increasing minor, we risk that for a component with last
version `1.2.3` the next master is `1.3.3` which evaluates higher that
the next final release `1.3.0`...
Amends commit 99885d9.

mender-deb-package: Amend version increment for "master" packages

---

.gitlab-ci.yml

This was just an optimization to speed up pipelines, but under certain
scenarios it does not work as expected. Disabling for now until the
author gets time for value add experimentation...

pipeline: Disable reuse of upstream images

---

tests/test_package_client.py

After https://github.com/mendersoftware/mender/pull/873 there is an
extra step in the interactive dialog.

Fix TestPackageMenderClientInteractive after introducing a new step

---

Dockerfile

So that we can build mender-gateway and are a bit more future proofed.

Update golang version to latest 1.17

---

recipes/mender-monitor/debian-master/rules

We fixed this once, see cad433a, but by mistake the fix got lost when we
duplicated the recipes for mender-monitor > 1.0.x

MEN-5390: Fix (again) the binary symlinks for mender-monitor

---

scripts/install-mender.sh

Commercial demo packages need to be filtered out when installing from
repository and filtered in when installing from direct downloads.

MEN-5400: install-mender.sh: Fix install of demo commercial packages

---

recipes/mender-client/debian-2.4.x/control

Porting fix 1d21cab from master recipe to the still supported versions
of mender-client.

debian-2.4.x: Add libffi6 as a depency for the client

---

.gitlab-ci.yml

pipeline: publish mender-monitor: Add guards around demo package
Which does not exist for 1.0.x builds
pipeline: publish commercial: comment out the "latest" updates
The logic is not good enough and would have overridden recently released
mender-monitor 1.1.0 with soon to be released mender-monitor 1.0.1 (both
are final tags!)
We are following up in MEN-5029.

pipeline: fixes for bugfix release

---

scripts/install-mender.sh

The mender-monitor package does not install the enabled directory.
This is done on mender-monitorctl create. But when running the enabled command,
the directory is not created.

install the missing enabled directory

---

mender-deb-package

Amends commit 7530e57.
The above commit appended the distro and codename to DEB_VERSION but
this regex was not updated. Instead of overcomplicating the regex, check
for VERSION instead.

mender-deb-package: Fix regex for detecting tags

---

scripts/install-mender.sh

The install-mender.sh is now capable of detecting the LSB distro and
version, and selecting the distro/version-specific APT repository.
Changelog: title

feat: update `install-mender.sh` to detect LSB distro/version

---

mender-deb-package

The logic was wrong: we only want in stable final tags, build tags and
master versions go to experimental.
Amends commit 7530e57.

mender-deb-package: Fix detection of distribution based on tags

---

Dockerfile

This reverts commit dc30bea920e7787e2ca38ac372c8948ad337f157.

Revert "temporary workaround for ubuntu archive being down"

---

.gitlab-ci.yml

The "latest" link needs to be reworked in MEN-5029, but for the "master"
one we can enable it in the meanwhile.

pipeline: Re-enable master publishing for commercial packages

---

docker-build-package

This one addresses the problem of checksums mismatch for debian.tar.xz files, which are generated per distribution,
e.g.: `mender-client_3.3.0~git20220215.a905a0a-1+debian+buster+builder474683108.debian.tar.xz`, but contain 
the timestamp of generation and the username and user email in the debian/changelog. It ensures that the debian/changelog will be the same across all the architectures.
The other option is to create source packages per distribution, right now we are building sources for all cases.
ChangeLog:title

Fixes to debian.tar.xz files generation.

---

scripts/install-mender.sh

When supplied with `--demo` flag, the script will download and extract
the examples tarball of mender-gateway containing configuration file,
certificate and key for demo purposes.

MEN-5475: install-mender.sh: Support setting up mender-gateway for demo

---

scripts/install-mender.sh
tests/test_package_addons.py

This reverts commit 842c78efae610ceff5dac96b198925f5f53485ee.

Revert "install the missing enabled directory"

---

Dockerfile

It is unknown why, but it seems to work to add them manually.

Work around failure to resolve foreign arch deps in ubuntu/focal.

---

.gitlab-ci.yml

It seems that the publishing by accident, when reworked from:
https://github.com/mendersoftware/mender-dist-packages/blob/ae161329b59def05508ff2405bc54cea66d29927/.gitlab-ci.yml#L512-L518
Got rewritten to publish to the versioned package directory by accident.
The fix is a simple naming change back to /latest/ from $PUBLISH_PACKAGE_VERSION

ci(publish): fix the latest commercial package publishing

---

.gitlab-ci.yml
mender-deb-package

exclude .git and debian directories in orig file, use one orig file.
* build the orig.tar file by ourselves: excluding .git (not needed) and
debian (present in debian.tar file) directories
* tar produces different checksums for identical directories occupying
different inodes: in the publish stage we copy one and same orig file
(the contents of it never change between distros, release names, archs)
Ticket: QA-404

do not package .git or debian directory, publish same orig file

---

.gitlab-ci.yml

Avoid the following error:
ERROR: unable to select packages:
openssh-client-common-9.0_p1-r1:
breaks: openssh-client-default-9.0_p1-r2[openssh-client-common=9.0_p1-r2]
Ticket: None

ci: install openssh-client instead of openssh

---

scripts/install-mender.sh

Commercial packages are downloaded manually via curl. Remove them after
successful install.

chore(install-mender.sh): Clean-up working dir after install

---

tests/test_package_gateway.py

This test does not run on PRs, so the mistake went unnoticed on the
review.

test(test_mender_gateway): Amend commit d840e586

---

mender-deb-package

Amends commit 2cd7728fc15b9816781d9ac8ac9de0995c72aa9a
This is necessary to produce identical tarballs (same checksums).

fix(mender-deb-package): Set mtime before use

---

mender-deb-package

Behold: run two pipelines in master and get the different chksums for orig files.
At the same time the orig files in one pipeline is the same (as it should be).
```
#diff mender-client_3.4.0~git20220906.783b4b7.orig.tar.gz.hx re-run/mender-client_3.4.0~git20220906.783b4b7.orig.tar.gz.hx
1c1
< 00000000  1f 8b 08 00 f8 5b 17 63  00 03 ec 5c eb 76 db 46  |.....[.c...\.v.F|
---
> 00000000  1f 8b 08 00 07 63 17 63  00 03 ec 5c eb 76 db 46  |.....c.c...\.v.F|
```
fun facts: gzip header:
```
+0 +1 +2 +3 +4 +5 +6 +7
1f 8b 08 N1 T1 T2 T3 T4
```
`1f 8b` -- magic number
`08` -- deflate
N1 -- flags
T1,T2,T3,T4 -- four bytes of timestamp
Hence proposed fix to include `-n` in gzip flags.
Ticket: None

fix: Different pipelines produce different gzip headers in orig files.

---

scripts/install-mender.sh

Previously we were selecting "latest lts" Mender release as the source to decide which version of the commercial packages to install instead of "latest" Mender release, as it used to be before 6f6bc20b.

MEN-5941: fix(install-mender.sh): correctly install "latest" for commercial pkgs

---

.gitlab-ci.yml
docker-build-package

The publication of the packages to the apt-repo left some orig files.
It turns out those were unreferenced orig files coming from two sources:
* opensource/orig/ directory: where we store the orig file in ci pipeline
* orig files copied during the binary package build that got propagated
but never had an entry in the .changes file
We do not need to publish the `orig` directory nor the unreferenced
orig files. This patch takes care of that.
Ticket: MEN-5879

feat: Do not publish more orig files than needed

---

.gitlab-ci.yml

This is now removed from the docs, and hence is no longer needed.
Ticket: MEN-5907

ci: remove the publication of the mender-docs client download link 

---

.gitlab-ci.yml

As a follow-up from 03d5e23 which went missing at 555b8d2.

ci: Clean-up unused variables

---

docker-build-package

This will also have to be re-enabled with MEN-6579.

ci: Skip building source packages

---

docker-build-package

While introducing support for C++ sources we have broken support for golang sources. See MEN-6579.
While we fix the mentioned issue, we can use a fixed version on master to keep the pipelines running.

ci: Pin the builder image to an specific version

---

.gitlab-ci.yml
scripts/install-mender.sh

Ubuntu Bionic standard LTS support is EOL.

QA-600: chore: Deprecate Ubuntu Bionic debian packages

---

docker-build-package

This is just a clean-up: this variable is not used from inside the container.

ci: Do not pass `MENDER_PRIVATE_REPO_ACCESS_TOKEN` to the container

---

tests/conftest.py

Clears `DeprecationWarning`. See:
https://peps.python.org/pep-0632/#migration-advice

chore: Migrate from deprecated distutils

---

mender-deb-package

Note that the submodules are still doing full clones. Otherwise the cloning fails for some submodules due to objects being "unadvertised".

perf: Switch to shallow git clones

---

recipes/mender-connect/debian-master/control

It requires either `mender-client` or `mender-auth`, which is one of the new packages being distributed as part of Mender client 4.0 onwards.

MEN-6858: Update `Depends` for supported `mender-connect` recipes

---

docker-build-package

The C++ client has now landed on the master branch.

MEN-6569: Switch back `mender` upstream to `mendersoftware`

---

mender-deb-package
tests/test_package_client.py

The patch only exists for `mender-client` 4.0 onwards.

Misc fixes for building and testing `mender-client` golang and tagged versions

---

.gitlab-ci.yml

This mistake came in from the `feature-c++-client` branch but because we didn't had there privileges to run commercial tests it went unnoticed.
Thank you Ole for your over-the-shoulder review.

ci: Fix missing newline escape

---

recipes/mender-client/debian-master/rules
recipes/mender-flash/debian-master/rules

This was added unintentionally and is causing trouble for Ubuntu distributions in our APT repositories. See JIRA ticket for more details.

MEN-6915: Remove debug symbols packages for the C++ recipes

---

mender-deb-package

Unfortunately we rely on all tags being fetched, so we cannot use shallow clones. Use a shallow clone + `git fetch --tags` is the same as doing a full clone in the first place.
Ticket: MEN-6914
This reverts commit 73ab939e77b8aeeb948a3ed70d96d9fb5aa6cef9.

MEN-6914: Revert "perf: Switch to shallow git clones"

---

.gitlab-ci.yml

The `rules` were being overridden in the child jobs and was not possible to skip the tests anymore.

ci: Restore functionality to skip tests

---

recipes/mender-flash/debian-master/control

fix: `mender-flash` should not depend on anything

---

recipes/mender-client/debian-master/mender-auth.install
recipes/mender-client/debian-master/mender-update.install
tests/test_package_client_cpp.py

* MEN-6941: Correct path for the demo certificate
* MEN-6942: Add missing D-Bus policy file
* Move identity scripts to the right package

Misc fixes for `mender-client` packages

---

scripts/install-mender.sh
tests/test_install_mender_sh.py

Related to the C++ update, where `mender-setup` is its own standalone tool and systemd services have been split.

MEN-6939: Update script for the new packages

---

recipes/mender-client/debian-master/mender-auth.postrm
recipes/mender-client/debian-master/mender-auth.preinst
recipes/mender-client/debian-master/mender-update.postrm
recipes/mender-client/debian-master/mender-update.preinst
recipes/mender-client/debian-master/postinst
tests/test_install_mender_sh.py

Based on the research from Kristian Amlie. See:
* https://github.com/kacf/mender-dist-packages/commit/0dac3e66097aa54fdb071ea3492a14c8840654dc
With the new packaging, the files that used to belong to `mender-client` are now owned by `mender-auth` and `mender-update`.
Add `preinst` scripts to the new packages to divert the files and a `postinst` to `mender-client` to restore the diversions. See inline comments for more context.
Added a test to verify the upgrade path.

MEN-6945: Handle diversion of files when upgrading to `mender-client` 4.0

---

mender-deb-package
recipes/mender-client/debian-3.5.x/control
recipes/mender-client/debian-3.5.x/postinst
recipes/mender-client/debian-3.5.x/postrm
recipes/mender-client/debian-3.5.x/preinst
recipes/mender-client/debian-master/mender-auth.postrm
recipes/mender-client/debian-master/mender-update.postrm
recipes/mender-client/debian-master/postinst
tests/helpers.py
tests/test_dist_packages_versions.py
tests/test_install_mender_sh.py
tests/test_package_addons.py
tests/test_package_app_update_module.py
tests/test_package_client.py
tests/test_package_client_cpp.py
tests/test_package_client_dev.py
tests/test_package_flash.py
tests/test_package_gateway.py
tests/test_package_setup.py
tests/test_package_snapshot.py
tests/test_package_tools.py

* fix: Add placeholders for debhelper for `mender-client` master
These are needed in order to the systemd services to be started and
stopped automatically by `apt-get install` or `remove`.
* fix: Support downgrade of `mender-client` from 4 to v3
This commit consist on various parts:
* Introduce an epoch for all `mender-client` package builds so that we
can publish a `1:3.5.2` that will be upgradable from already
published `4.0.0` version. See:
https://www.debian.org/doc/debian-policy/ch-controlfields.html#version
* Add `preinst` and `postrm` scripts on the 3.5.x series to detect
an "upgrade" from v4 and:
* Take back ownership of the configuration files
* Disable `mender-authd` and `mender-updated` systemd services as
this was missing from the first publishing of the packages (see
previous …

MEN-6965: Support downgrade of `mender-client` from 4 to v3

---

recipes/mender-client/debian-master/control

Honestly I think this is a mistake by the upstream maintainers. Preumably it's because systemd is now providing dbus services, but this should not affect which package you need to depend on, at least not in a stable release.

Add libsystemd-dev as a build dependency for mender-client.

---

recipes/mender-app-update-module/debian-master/control
recipes/mender-configure/debian-master/control
recipes/mender-connect/debian-master/control
recipes/mender-monitor/debian-master/control

Besides `mender-client`, they need to accept also either `mender-auth` or `mender-update` as a replacement.
Note that `mender-connect` was correct, we are only re-ordering it for consistency with the rest.

MEN-7010: Fix `Depends` metadata for the Mender addons

---

.gitlab-ci.yml
docker-build-package
mender-deb-package
tests/test_dist_packages_versions.py
tests/test_package_addons.py

So that we can publish new packages of already released software.

MEN-7010: Support for overriding the Debian suffix in the package version

---

scripts/install-mender.sh
tests/test_install_mender_sh.py

From now on, mender-client4 will be a default component in place of mender-client; however, the script falls back to mender-client (legacy, go client) for Ubuntu jammy and focal and for Debian bullseye and buster. As we don't support just yet other distributions, it means that the only way to install the Mender Client version 4 is to specify its components explicitly from the command line. In the future, when we'll support other distributions (e.g., bookworm), mender-client4 will be the default.

feat: add support for mender-client4, mender-auth and mender-update components

---

tests/test_install_mender_sh.py

* test: Remove temporary middle step for `mender-configure`
The new package with the correct dependencies is already in production.
* test: Remove explicit install of `mender-update`
With the new production packages, this is not required anymore.

test: Clean-ups after publishing the new packages

---

tests/test_install_mender_sh.py

This reverts commit d3f5a5991391fff1f067ad2c4cc1d72229eb2110.
We cannot remove the explicit install of `mender-update` because the test will fail with as follows if the add-on packages (e.g., `mender-connect`) are not upgraded at the same time when upgrading from `mender-client` to `mender-client4`:
```
The following packages have unmet dependencies:
mender-client4 : Conflicts: mender-client but 1:3.5.2-1+debian+buster is to be installed
E: Unable to correct problems, you have held broken packages.
```
This happens on release pipelines, where we build `mender-connect` and `mender-configure` using an old tag, therefore not triggering an upgrade at the same time we install `mender-client4` to upgrade the Mender client.

revert: "test: Remove explicit install of `mender-update`"

---

recipes/mender-client4/debian-master/control
tests/test_package_client_cpp.py

When cross-compiling on armhf, we use a _hack_ to set the dependencies. If in use, it needs to be set for every package in the `control` file.
The test was passing by mistake.

MEN-7048: Missing `Depends` field for `mender-client4` armhf

---

.gitlab-ci.yml

When the code reaches `production`, the only thing relevant part of the pipeline is the install script and its tests.

ci: Disable building and testing packages in `production`

---

mender-deb-package

It seems like `buster-backports` distribution (backports for today's oldoldstable) has been removed from `deb.debian.org`.

build: Use Debian archives for `buster-backports`

---

scripts/install-mender.sh

To avoid errors like:
$ mender setup
ERRO[0000] Error loading configuration from file: /etc/mender/mender.conf (open /etc/mender/mender.conf: permission denied) ERRO[0000] open /etc/mender/mender.conf: permission denied
Ticket: None

fix: makes sure mender setup can run with right permissions

---

.gitlab-ci.yml

chore: aws command not found in .template:publish:s3:apt-repo

---

recipes/mender-configure/debian-master/control

Otherwise if the package is missing the install fails with:
```
...
Setting up mender-configure-demo (1.1.2-2+ubuntu+jammy) ...
cat: /etc/timezone: No such file or directory
dpkg: error processing package mender-configure-demo (--configure):
installed mender-configure-demo package post-installation script subprocess returned error exit status 1
Errors were encountered while processing:
mender-configure-demo
E: Sub-process /usr/bin/dpkg returned an error code (1)
```
It does not happen in real life because this package is installed by default in Debian/Ubuntu. But it fails on a vanilla Ubuntu Docker image, for example.

fix: Add `tzdata` dependency to `mender-configure-timezone`

---

.gitlab-ci.yml

Out of public runners, also for performance reasons because the job is painfully slow.
Ticket: SEC-1133

Move publish:s3 job to hetzner

---

.gitlab-ci.yml

IMDS is an api service available within AWS. AWS cli by default is trying to get metadata informations from the address 169.254.169.254, which is the internal IMDS endpoint. Our pipelines run in Hetzner and GCP, where this service is not available, and every aws cli command time out for about 5, slowing down the pipelines in the long run.
Ticket: QA-751

perf: speed up aws cli by ignoring imds

---

.gitlab-ci.yml

Missing from commit d07fd60, where we prevented the publish on the APT repos but forgot about the direct uploads to S3 for commercial packages.

MEN-7731: Do not publish cross-compiled Debian armhf commercial packages

---

.gitlab-ci.yml

Make sure the rules match all (or many) of the future major releases.

ci: Fix rules to actually run tests for `mender` 5.x

---

.gitlab-ci.yml

From time to time gitlab.com is timing out when issuing docker login, this change allow for a retry
This should solve this case: https://gitlab.com/Northern.tech/Mender/mender-dist-packages/-/jobs/9126549483
Ticket: QA-921

ci: docker login retry

---

mender-deb-package

To align with new `mender-artifact` requirements.

MEN-8141: Update go version to 1.22

---

.gitlab-ci.yml

Everyday we have a failure of this sort:
docker: error during connect: Head "https://docker:2376/_ping": dial tcp: lookup docker on 127.0.0.11:53: server misbehaving.
https://gitlab.com/Northern.tech/Mender/mender-dist-packages/-/jobs/9593744363
PoC type of approach (I do not know how to do retry conditionally): retry job on simple docker not running.
Ticket: None

ci: retry on docker not running.

---

recipes/mender-artifact/debian-master/control

Requiring `ssh` means the SSH client as well as daemon/server is installed, pulling in lots of extra dependencies like Systemd, DBus, etc. `mender-artifact` only requires the `ssh` command, i.e. the client.
Ticket: MEN-8433

fix: Require ssh-client for mender-artifact not ssh

---

recipes/mender-client4/debian-4.0.x/control
recipes/mender-client4/debian-master/control

Otherwise installation of `mender-client4` pulls in the lastest available versions of `mender-auth` and `mender-update`, no matter what the version of `mender-client4` is. We need all of them to be in sync.
Ticket: MEN-8476

fix: mender-client4 package should require same version of auth and update

---

scripts/install-mender.sh

Ticket: None
Changelog: Use the new `device-components` repository for packages. All new device components are published to this repository in favor of the old `debian` repository.

feat: use the `device-components` repository

---

.gitlab-ci.yml

The var GPG_PRIV_KEY_BUILD is not used, replaced by MENDER_PRIVATE_GPG_KEY_BUILD
Ticket: QA-791
Linked to: https://github.com/mendersoftware/sre-tools/pull/424

ci: clean up unused var

---

.gitlab-ci.yml
tests/conftest.py
tests/helpers.py
tests/test_package_addons.py
tests/test_package_app_update_module.py
tests/test_package_client_cpp.py
tests/test_package_flash.py
tests/test_package_setup.py
tests/test_package_snapshot.py

Instead of using a dind container running a container running QEMU running ARMv6 Rapberry Pi OS.
TODO: **mender_test_containers revision fixup after merge**
Ticket: QA-1086

ci: Test packages in an ARM64 Debian 11 container

---

.gitlab-ci.yml
README.md
docker-build-package
mender-deb-package

We no longer support ARMv6 packages for Raspberry Pi.
Ticket: QA-1087

ci: Don't build Raspberry Pi OS armhf (ARMv6) packages

---

.gitlab-ci.yml

mender-artifact is commonly used in CI/CD pipelines which often run on ARM64 these days. Also, we need ARM64 containers for MacOS users that want to use our "tool containers" because the new machines running MacOS are ARM64.
Ticket: MEN-8685

ci: Build workstation-tools for ARM64

---

README.md

The container images are no longer provided and built in this repository and the package building instructions definitely deserve more details.
Ticket: QA-867

chore: Update package build instructions in README
