- Dockerfile
- mender-deb-package
See related [mender-docs PR](https://github.com/mendersoftware/mender-docs/pull/676)
> Mender client conflict old package

- Dockerfile
- tests/helpers.py
Modified a bit the Dockerfile also to optimize cache usage when
upgrading Mender source.
> Update package config for Mender 2.0.1 release

- README.md
This information is synchronized with mendersoftware/mender
Signed-off-by: Mirza Krak <mirza.krak@northern.tech>
> README: update 'Connect with us' information and add 'Authors section

- Dockerfile
- tests/helpers.py
> Upgrade to Mender client 2.1.0.

- .gitlab-ci.yml
- README.md
- docker-mender-dist-packages
> Add a wrapper around Docker build/run to simplify usage

- Dockerfile
- tests/test_package_client.py
Following rename done in master, see MEN-2984
> Update service name and fix acceptance tests

- .gitlab-ci.yml
> Install awscli in the publish:latest job

- .gitlab-ci.yml
While also giving it the name latest.
> fix: Explicitly upload the deb_package to the /latest/ bucket

- .github/dependabot.yml
- .gitlab-ci.yml
- Dockerfile
* [pipeline] Minor beautification: image definition
* Introduce dependabot for pip and gitmodules
* Update golang to version 1.14.7
> Misc: dependabot and golang version

- tests/requirements.txt
> Dependabot updates

- scripts/install-mender.sh
- tests/test_install_mender_sh.py
> install-mender.sh: client+shell install script

- .gitlab-ci.yml
one missing acc criterion for https://tracker.mender.io/browse/MEN-4150.
> gitlab: publish install-mender.sh to s3

- scripts/install-mender.sh
changelog: none
Signed-off-by: Marcin Chalczynski <m.chalczynski@gmail.com>
> install-mender: remove unused func

- recipes/mender-client/debian-master/control
Changelog: title
Signed-off-by: Fabio Tranchitella <fabio@tranchitella.eu>
> MEN-4072: add glib dependency to the mender-client Debian package

- .gitlab-ci.yml
Signed-off-by: Fabio Tranchitella <fabio@tranchitella.eu>
> Set the content-type to text/plain for scripts/install-mender.sh

- Dockerfile
At least the very first layer can be reused across architectures...
> Dockerfile: optimization for cache reuse

- .gitlab-ci.yml
Using the new DinD setup for mender-qa slaves.
> [pipeline] Update base image for tests to docker:19

- .gitlab-ci.yml
master branch will upload to staging, which is hosted in the "staging"
subfolder of the bucket, and production branch will upload to the
bucket root.
> MEN-4436: Introduce staging and production uploads for install-mender.sh.

- scripts/install-mender.sh
- tests/test_install_mender_sh.py
> Add mender-configure to default components and add repo tests.

- recipes/mender-configure/debian-master/control
- recipes/mender-configure/debian-master/mender-configure-demo.install
- recipes/mender-configure/debian-master/mender-configure-timezone.install
- recipes/mender-configure/debian-master/mender-configure.dirs
- recipes/mender-configure/debian-master/mender-configure.install
- recipes/mender-configure/debian-master/rules
- scripts/install-mender.sh
Best reviewed commit by commit.
> Changes needed for mender-configure demos.

- recipes/mender-configure/debian-master/control
> MEN-4579: Add missing dependency on jq for the demo conf scripts.

- recipes/mender-configure/debian-master/mender-configure-demo.postinst
> MEN-4594: add postint script to install the default configuration

- tests/test_install_mender_sh.py
> MEN-4481: Promote mender-configure to a stable component

- recipes/mender-client/debian-master/control
- recipes/mender-client/debian-master/mender-client-dev.install
- tests/test_package_client_dev.py
> MEN-4105: new pkg mender-client-dev to distribute the D-Bus interface files

- scripts/install-mender.sh
> Fix: Overwrite the existing mender.list file, instead of appending

- .gitlab-ci.yml
> Fix incorrect source path when copying not-latest packages.

- tests/test_install_mender_sh.py
Upstream raspbian.raspberrypi.org has changed the suite name for buster
from "stable" to "oldstable", so the test client needs to explicitly
accept the change before running other apt-get commands.
Moved the script_server fixture to a class level marker and removed the
redundant setup_tester_ssh_connection_f fixture marker (explicit in the
method's arguments).
> test_install_mender_sh.py: Fix apt-get error after suite rename

- tests/test_install_mender_sh.py
The purpose of these tests are on verifying the different options of the
install script... and for that we don't need QEMU or ARM emulation.
With this change, we migrate all the tests to use a debian:buster
container, and add *one* test for Raspberry OS.
Locally the tests run now in 10 minutes: 3 for the converted tests and 7
for the new Raspberry OS test.
> test_install_mender_sh.py: Run tests on x86-64 container

- .gitlab-ci.yml
> pipeline: apt-repo: Correctly evaluate build tags and git versions

- .gitlab-ci.yml
> pipeline: publish:s3:apt-repo: Add gpg

- .gitlab-ci.yml
> pipeline: Remove obsolete variable PUBLISH_LATEST_CLIENT_PACKAGE

- tests/test_package_client.py
The new client has changed the route taken for authorization in the state
machine, hence a new output match is needed.
> test: Add a check for the output from the newer client

- .gitlab-ci.yml
The logic was not ready for multiple similarly named packages.
> chore: fix the publishing of the monitor-demo packages

- recipes/mender-client/debian-master/control
> Add libffi6 as a depency for the client

- recipes/mender-client/debian-2.4.x/control
- scripts/install-mender.sh
> Sync production branch with master

- recipes/mender-monitor/debian-master/mender-monitor-demo.install
- recipes/mender-monitor/debian-master/mender-monitor.dirs
> Add the missing enabled and available directories during install

- Dockerfile
> temporary workaround for ubuntu archive being down

- Dockerfile
- docker-build-package
- mender-deb-package
- tests/test_dist_packages_versions.py
> MEN-5405 Debian Source packages.

- .gitlab-ci.yml
> MEN-5405 Publish debian source packages

- recipes/mender-connect/debian-master/control
- tests/conftest.py
- tests/test_package_addons.py
> Restore the mender-connect dependency and re-enable test

- .gitlab-ci.yml
fixes: https://gitlab.com/Northern.tech/Mender/mender-dist-packages/-/jobs/2097671614
> Debian packages publication fixes: properly call aws s3 cp

- tests/test_package_client.py
After modification in the client state machine. See:
https://github.com/mendersoftware/mender/pull/943
Add a new message to the criterion for the first state machine
transition and give more time to get to the authorization failure
(because now bootstrap keys get generated _after_ the transition to
inventory-update state).
> test_package_client.py: Fix full cycle detection

- .gitlab-ci.yml
> .gitlab-ci.yml: Fix typo in .template:publish:s3

- Dockerfile
- mender-deb-package
> MEN-5459 Install go based on the source repository preferences.

- scripts/install-mender.sh
Previously `--commercial` flag would install all commercial components,
but `mender-gateway` should not be installed by default.
Rework a bit the script to have the "default" and "demo" concepts also
applied to commercial packages.
> install-mender.sh: Do not install mender-gateway by default

- recipes/mender-monitor/debian-master/mender-monitor-demo.install
> chore: removal of examples/dockerevents

- docker-build-package
This is temporary in nature and will be resolved in QA-404 once it's done.
> chore: disable the source build packages

- .gitlab-ci.yml
> chore: fix the copy-paste error in apt-repo publish

- docker-build-package
This reverts commit d9ea6e5eaead3dcb40986b3ec20e5d3dd9993fb6.
> chore: Revert "chore: disable the source build packages"

- .gitlab-ci.yml
- docker-build-package
- mender-deb-package
> chore: A more elegant approach of using a reference orig file.

- mender-deb-package
> chore: Fixing the case of commercial packages: no orig file created then

- .gitlab-ci.yml
> chore: do not call build package in orig stage for commercial packages.

- .gitlab-ci.yml
- scripts/install-mender.sh
> feat: Add Ubuntu 22 packages

- scripts/install-mender.sh
> feat: Install the packages from the versions in versions.json

- recipes/mender-client/debian-master/postrm
> MEN-5403: fix(postrm): Successfully remove package with mender.conf missing

- scripts/install-mender.sh
Amends commit a17b523c7a986f37ccefe4fc7f59030d98e6643c
> chore(install-mender.sh): Clean-up also example package after install

- scripts/install-mender.sh
Ticket: [MEN-5927](https://tracker.mender.io/browse/MEN-5927)
> chore: Stop using deprecated apt-key when installing repo

- mender-deb-package
- tests/test_package_client.py
With the newest client, this is no longer installed, and hence has to be removed.
Ticket: MEN-5976
> test: delete the artifact_info file checks

- .gitlab-ci.yml
- docker-build-package
- mender-deb-package
- scripts/install-mender.sh
- tests/requirements.txt
- tests/test_package_client.py
> Merge master into production

- scripts/install-mender.sh
Ticket: MEN-5928
Signed-off-by: Mikael Torp-Holte <mikael.torp-holte@northern.tech>
> fix: install experimental debian packages in install-mender.sh

- Dockerfile
- README.md
> chore: update bug tracker link

- tests/requirements.txt
> fix: added missing module

- mender-deb-package
> feat: upgrade golang to 1.21.0

- recipes/mender-client/debian-master/control
> fix: mender-client meta-recipe should rely on mender-{auth,update}

- mender-deb-package
Follows from:
* https://github.com/mendersoftware/mender-dist-packages/pull/366
> Miscellaneous chores around cross-compilation

- .gitlab-ci.yml
Do only the ones that are likely to be needed on a manual run from GUI.
> ci: Enrich (some) variables definitions

- scripts/install-mender.sh
This reverts commit 1d628f366541b2481aab58f7d3defd685cbbef80.
> Revert "chore: Update script for the new packages"

- scripts/install-mender.sh
> chore: improve the autodetection of `mender-setup` vs. `mender setup`

- .gitlab-ci.yml
> test: building on a virtual arm server

- .gitlab-ci.yml
- scripts/install-mender.sh
- scripts/tests/test_install_mender_sh.py
> feat: always install mender-client4 if the channel is `experimental`

- .gitlab-ci.yml
> chore: save additional information in the /incoming flag

- .gitlab-ci.yml
Using Dependency proxy to save docker pull rate limit
Ticket: QA-705
> ci: using Depencency proxy

- .gitlab-ci.yml
> chore: using selector form

- .gitlab-ci.yml
To allow users without top group permissions to run jobs
Ticket: None
> ci: using direct subgroup dependency proxy

- tests/test_package_client_cpp.py
See:
* https://github.com/mendersoftware/mender/pull/1693
> test: Remove check for moved update modules

- recipes/mender-artifact/debian-master/control
- tests/test_package_tools.py
> fix: Update mender-artifact Debian dependencies

- .gitlab-ci.yml
- tests/conftest.py
- tests/helpers.py
> ci: Run package tests in an ARMv7 Debian container

- .gitlab-ci.yml
- scripts/install-mender.sh
> chore: Add Debian 13 support

- .gitlab-ci.yml
> ci: Use latest Debian version as CI image

- tests/helpers.py
So that it can easily be modified locally when running tests.
> refac: Use a define for the default architecture

- tests/conftest.py
For reasoning see:
* https://github.com/mendersoftware/mender-test-containers/pull/662
> test: Update version of Client used for pre-configured tests
